apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rollback-alert
  namespace: monitoring
  labels:
    role: alert-rules
    release: monitoring
spec:
  groups:
  - name: blue-green
    rules:
    - alert: GreenUnhealthy
      expr: | 
        (sum(rate(container_network_receive_bytes_total{namespace="blue-green-demo",pod=~"blue-green-backend-.*"}[1m]))
        + 
        sum(rate(container_network_receive_bytes_total{namespace="blue-green-demo",pod=~"blue-green-frontend-.*"}[1m])))
      for: 30s
      labels:
        severity: critical
      annotations:
        summary: "Green environment is broken - rollback triggered"
        description: "DevOps Project Green frontend/backend returned an HTTP 5xx error rate greater than 5% for over 30s."
