apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-frontend
  namespace: blue-green-demo
  labels:
    app: frontend
    version: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: green
  template:
    metadata:
      labels:
        app: frontend
        version: green
    spec:
      containers:
      - name: frontend
        image: devops-proj/frontend:green
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-backend
  namespace: blue-green-demo
  labels:
    app: backend
    version: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      version: green
  template:
    metadata:
      labels:
        app: backend
        version: green
    spec:
      containers:
      - name: backend
        image: devops-proj/backend:green
        imagePullPolicy: IfNotPresent
        env:
        - name: VERSION
          value: "green"
        ports:
        - containerPort: 5000
