apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monitor
  namespace: monitoring
  labels:
    release: monitoring  # Target the prometheus community helm release
spec:
  namespaceSelector:
    matchNames:
    - blue-green-demo
  selector:
    matchLabels:
      app: backend
  endpoints:
  - port: "5000"
    path: /metrics
    interval: 10s
