{
 "title": "Tasks API - DevOps Demo",
 "tags": [
  "devops",
  "demo"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "HTTP Request Rate (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(promhttp_metric_handler_requests_total[1m])",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Go Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "goroutines" }
   ]
  },
  {
   "title": "Process Memory (RSS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "RSS" }
   ]
  },
  {
   "title": "Prometheus Scrape Targets Up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  }
 ]
}